<?php
namespace app\admin\controller;

use app\admin\controller\Base;
use think\Cookie;

class Index extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if($this->checkUnLogin()){
            return $this->fetch('index/login');
        }
    }

    /**
     * 默认首页
     * @return mixed
     */
    public function index()
    {
        if(empty($this->adminInfo)){
            return $this->fetch('index/login');
        }else{
            $this->assign('adminInfo',$this->adminInfo);
            $this->assign('url',url('index/welcome'));
            return$this->fetch('index/index');
        }
    }

    /**
     * 欢迎页
     */
    public  function welcome(){
        $server = $this->request->server();
        $this->assign('server',$server);
        return  $this->fetch('index/welcome');
    }
    /**
     * 管理员登录
     */
    public function login()
    {
       $post = $this->request->post();
       if(!empty($post)){
           $post['ip'] = $this->request->ip(0,1);
           $res = adminforwarding('admin','login',$post);
           if($res['data']){
               //存cookie加密
               Cookie::set('primarykey',encrypt($res['data']));
               return ['message'=>'ok','status'=>1];
           }else{
               return ['message'=>$res['message'],'status'=>0];
           }
       }else{
           if(empty($this->adminInfo)){
               return $this->fetch('index/login');
           }
           return $this->fetch('index/index');
       }
    }

    /**
     * 退出
     */
    public function loginOut(){
        if(!empty($this->adminInfo)){
            $adminInfo =  $this->adminInfo;
            $arr['u_last_time'] = $adminInfo['u_login_time'];
            $arr['u_last_ip'] = $adminInfo['u_login_ip'];
            $arr['u_id'] = $adminInfo['u_id'];
            $arr['op'] = 'loginOut';
            adminforwarding('admin','updateAdminStatus',$arr);
        }
        Cookie::clear();
        return $this->redirect('index/login');
    }
}
